### ISSUE TITLE
Error getting CONUS404 dataset

### ISSUE THREAD

**Issue by ShihengDuan** [hytest-org/hytest#464]
Hi,

I'm trying to access the CONUS404 daily output through ```conus404-daily-osn``` and get the following error. The code is from the demo notebook:
```
import xarray as xr
import xesmf as xe
import numpy as np
import fsspec
from matplotlib import path 
import intake
import os

hytest_cat = intake.open_catalog("https://raw.githubusercontent.com/hytest-org/hytest/main/dataset_catalog/hytest_intake_catalog.yml")
print(list(hytest_cat))
cat = hytest_cat['conus404-catalog']
dataset = 'conus404-daily-osn' 
cat[dataset]
ds = cat[dataset].to_dask()

```
Error message:
```
Traceback (most recent call last):
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/aiohttp/connector.py", line 1025, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/asyncio/base_events.py", line 1098, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/asyncio/base_events.py", line 1131, in _create_connection_transport
    await waiter
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/asyncio/sslproto.py", line 577, in _on_handshake_complete
    raise handshake_exc
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/asyncio/sslproto.py", line 559, in _do_handshake
    self._sslobj.do_handshake()
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/ssl.py", line 979, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:992)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/aiobotocore/httpsession.py", line 222, in send
    response = await session.request(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/aiohttp/client.py", line 581, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/aiohttp/connector.py", line 944, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/aiohttp/connector.py", line 1257, in _create_direct_connection
    raise last_exc
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/aiohttp/connector.py", line 1226, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/aiohttp/connector.py", line 1027, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host usgs.osn.mghpcc.org:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:992)')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/zarr/storage.py", line 1446, in __getitem__
    return self.map[key]
           ~~~~~~~~^^^^^
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/fsspec/mapping.py", line 155, in __getitem__
    result = self.fs.cat(k)
             ^^^^^^^^^^^^^^
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/fsspec/asyn.py", line 118, in wrapper
    return sync(self.loop, func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/fsspec/asyn.py", line 103, in sync
    raise return_result
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/fsspec/asyn.py", line 56, in _runner
    result[0] = await coro
                ^^^^^^^^^^
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/fsspec/asyn.py", line 461, in _cat
    raise ex
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/fsspec/asyn.py", line 245, in _run_coro
    return await asyncio.wait_for(coro, timeout=timeout), i
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/asyncio/tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/s3fs/core.py", line 1128, in _cat_file
    return await _error_wrapper(_call_and_read, retries=self.retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/s3fs/core.py", line 145, in _error_wrapper
    raise err
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/s3fs/core.py", line 113, in _error_wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/s3fs/core.py", line 1115, in _call_and_read
    resp = await self._call_s3(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/s3fs/core.py", line 365, in _call_s3
    return await _error_wrapper(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/s3fs/core.py", line 145, in _error_wrapper
    raise err
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/s3fs/core.py", line 113, in _error_wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/aiobotocore/client.py", line 391, in _make_api_call
    http, parsed_response = await self._make_request(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/aiobotocore/client.py", line 419, in _make_request
    return await self._endpoint.make_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/aiobotocore/endpoint.py", line 102, in _send_request
    while await self._needs_retry(
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/aiobotocore/endpoint.py", line 264, in _needs_retry
    responses = await self._event_emitter.emit(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/aiobotocore/hooks.py", line 66, in _emit
    response = await resolve_awaitable(handler(**kwargs))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/aiobotocore/_helpers.py", line 15, in resolve_awaitable
    return await obj
           ^^^^^^^^^
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/aiobotocore/retryhandler.py", line 107, in _call
    if await resolve_awaitable(self._checker(**checker_kwargs)):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/aiobotocore/_helpers.py", line 15, in resolve_awaitable
    return await obj
           ^^^^^^^^^
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/aiobotocore/retryhandler.py", line 126, in _call
    should_retry = await self._should_retry(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/aiobotocore/retryhandler.py", line 165, in _should_retry
    return await resolve_awaitable(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/aiobotocore/_helpers.py", line 15, in resolve_awaitable
    return await obj
           ^^^^^^^^^
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/aiobotocore/retryhandler.py", line 174, in _call
    checker(attempt_number, response, caught_exception)
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/botocore/retryhandler.py", line 247, in __call__
    return self._check_caught_exception(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/botocore/retryhandler.py", line 416, in _check_caught_exception
    raise caught_exception
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/aiobotocore/endpoint.py", line 183, in _do_get_response
    http_response = await self._send(request)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/aiobotocore/endpoint.py", line 287, in _send
    return await self.http_session.send(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/aiobotocore/httpsession.py", line 244, in send
    raise SSLError(endpoint_url=request.url, error=e)
botocore.exceptions.SSLError: SSL validation failed for https://usgs.osn.mghpcc.org/hytest/conus404/conus404_daily.zarr/.zmetadata Cannot connect to host usgs.osn.mghpcc.org:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:992)')]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/p/user_pub/climate_work/duan5/CONUS404/conus404.py", line 14, in <module>
    ds = cat[dataset].to_dask()
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/intake_xarray/base.py", line 69, in to_dask
    return self.read_chunked()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/intake_xarray/base.py", line 44, in read_chunked
    self._load_metadata()
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/intake/source/base.py", line 84, in _load_metadata
    self._schema = self._get_schema()
                   ^^^^^^^^^^^^^^^^^^
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/intake_xarray/base.py", line 18, in _get_schema
    self._open_dataset()
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/intake_xarray/xzarr.py", line 46, in _open_dataset
    self._ds = xr.open_dataset(self.urlpath, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/xarray/backends/api.py", line 573, in open_dataset
    backend_ds = backend.open_dataset(
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/xarray/backends/zarr.py", line 1016, in open_dataset
    store = ZarrStore.open_group(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/xarray/backends/zarr.py", line 469, in open_group
    zarr_group = zarr.open_consolidated(store, **open_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/zarr/convenience.py", line 1360, in open_consolidated
    meta_store = ConsolidatedStoreClass(store, metadata_key=metadata_key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/zarr/storage.py", line 3046, in __init__
    meta = json_loads(self.store[metadata_key])
                      ~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/zarr/storage.py", line 1448, in __getitem__
    raise KeyError(key) from e
KeyError: '.zmetadata'
```
I'm not sure if the problem is on my end.

**Comment by ShihengDuan** [comment]
Different data sources show different error message. If I use ```conus404-daily-onprem```:
```
Traceback (most recent call last):
  File "/p/user_pub/climate_work/duan5/CONUS404/conus404.py", line 15, in <module>
    ds = cat[dataset].to_dask()
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/intake_xarray/base.py", line 69, in to_dask
    return self.read_chunked()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/intake_xarray/base.py", line 44, in read_chunked
    self._load_metadata()
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/intake/source/base.py", line 84, in _load_metadata
    self._schema = self._get_schema()
                   ^^^^^^^^^^^^^^^^^^
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/intake_xarray/base.py", line 18, in _get_schema
    self._open_dataset()
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/intake_xarray/xzarr.py", line 46, in _open_dataset
    self._ds = xr.open_dataset(self.urlpath, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/xarray/backends/api.py", line 573, in open_dataset
    backend_ds = backend.open_dataset(
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/xarray/backends/zarr.py", line 1016, in open_dataset
    store = ZarrStore.open_group(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/xarray/backends/zarr.py", line 469, in open_group
    zarr_group = zarr.open_consolidated(store, **open_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/zarr/convenience.py", line 1360, in open_consolidated
    meta_store = ConsolidatedStoreClass(store, metadata_key=metadata_key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/zarr/storage.py", line 3046, in __init__
    meta = json_loads(self.store[metadata_key])
                      ~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/duan5/mambaforge/envs/duan/lib/python3.11/site-packages/zarr/storage.py", line 1120, in __getitem__
    raise KeyError(key)
KeyError: '.zmetadata'
```

**Comment by amsnyder** [comment]
Hi there. That storage location was temporarily offline for annual maintenance. It should be online again. Could you see if you can access now?

**Comment by ShihengDuan** [comment]
Thanks for your update. I've tried again but the error persists.

**Comment by gtyree01** [comment]
Hello! I'm getting the same error when I run this demo notebook (last try running the code was 06/07/2024).

**Comment by amsnyder** [comment]
I can run the code above with no error. Can you double check that you have the python package `s3fs` installed?

**Comment by gtyree01** [comment]
@amsnyder Thank you for the rapid response! I do have s3fs installed, version 2024.5.0.

**Comment by ShihengDuan** [comment]
I just retried and it works for me. 
I have installed s3fs 2024.5.0.

**Comment by amsnyder** [comment]
@gtyree01 - you are still experiencing the error though?

**Comment by gtyree01** [comment]
@amsnyder Yes, I'm afraid so. I think it might have to do with a conflict with the py package fsspec (2024.5.0), since I got an error message mentioning fsspec when I installed s3fs. The versions I have installed are supposed to work well together though, so I'm not sure this is the issue.

**Comment by sfoks** [comment]
I had to update all the packages in my env for this error to go away. Sorry I don't have a clear sense of which package it was.

**Comment by gtyree01** [comment]
@sfoks Good to know, I'll try that.

**Comment by gtyree01** [comment]
@sfoks @amsnyder I'm afraid that the issue didn't resolve with a mass package update in my env.

**Comment by gtyree01** [comment]
It seems that the issue was probably with my environment set-up. Once I began working in the HyTEST Jupyter Server app on the USGS HPC that has the environment pre-configured, this issue resolved. Thanks all for the help!

**Comment by mirizarry-ortiz** [comment]
I am getting the same error even when using the pre-configured environment (following these instructions: https://hytest-org.github.io/hytest/environment_set_up/StartScript.html)
I am trying to access this dataset: dataset = 'conus404-hourly-ba-onprem'

**Comment by sfoks** [comment]
@mirizarry-ortiz Right now the CONUS404-BA on-prem had to be moved to Hovenweep because of storage issues, so access on the HyTEST Jupyter Server to "-on-prem" CONUS404BA won't work right now. Did you try the OSN version on the Jupyter Server? It might be a might slower but should work? Another option would be to tunnel into Hovenweep but I haven't tried this yet.

**Comment by mirizarry-ortiz** [comment]
@sfoks thanks for the update. I will try the OSN version!
